In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

In [2]:
df = pd.read_csv(r"C:\All project\Advanced Multi-Source Data Pipeline\crypto_data.csv")
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,79521.000000,1596907659479,1,1596917360999,3.401496e+10,79701.000000,...,2.008179e+07,2.100000e+07,126080.000000,-36.92831,2025-10-06T10:57:42.000Z,67.810000,1.171716e+05,2013-07-05T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2511.780000,306518201478,2,306518201478,1.198981e+10,2521.510000,...,1.220326e+08,NaN,4946.050000,-49.21649,2025-08-24T11:21:03.000Z,0.432979,5.800154e+05,2015-10-19T16:00:00.000Z,"{'times': 41.23061842109489, 'currency': 'btc'...",2026-09-09T09:14:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999752,183414602480,3,188880189741,5.250357e+10,0.999995,...,1.889271e+11,NaN,1.320000,-24.43837,2018-07-23T16:00:00.000Z,0.572521,7.462283e+01,2015-03-01T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,756.770000,100774371434,4,100774365637,9.948938e+08,757.670000,...,1.331614e+08,2.000000e+08,1369.990000,-44.76087,2025-10-13T00:41:24.000Z,0.039818,1.900491e+06,2017-10-18T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.430000,89895396694,5,143251551449,2.588803e+09,1.450000,...,9.998563e+10,1.000000e+11,3.650000,-60.71386,2025-07-17T19:40:53.000Z,0.002686,5.322878e+04,2014-05-21T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,official-trump,trump,Official Trump,https://coin-images.coingecko.com/coins/images...,2.260000,617543636,95,2260928999,1.587567e+08,2.290000,...,1.000000e+09,1.000000e+09,73.430000,-96.92074,2025-01-19T03:50:34.000Z,1.370000,6.501702e+01,2026-08-13T18:40:30.000Z,NaN,2026-09-09T09:14:20.000Z
96,ether-fi,ethfi,Ether.fi,https://coin-images.coingecko.com/coins/images...,0.630890,609010350,96,609010350,7.238132e+07,0.639674,...,9.653500e+08,1.000000e+09,8.530000,-92.60293,2024-03-27T15:14:46.000Z,0.266530,1.367049e+02,2026-06-05T19:19:15.000Z,NaN,2026-09-09T09:14:20.000Z
97,aerodrome-finance,aero,Aerodrome Finance,https://coin-images.coingecko.com/coins/images...,0.607918,599747778,97,1199852440,7.055795e+07,0.653594,...,1.973685e+09,NaN,2.320000,-73.76200,2024-12-07T06:00:38.000Z,0.000019,3.266525e+06,2023-10-16T17:23:50.000Z,NaN,2026-09-09T09:14:20.000Z
98,beldex,bdx,Beldex,https://coin-images.coingecko.com/coins/images...,0.075553,594556619,98,750847875,1.184372e+07,0.077927,...,9.939514e+09,NaN,0.450785,-83.23974,2018-12-16T16:00:00.000Z,0.000275,2.735518e+04,2019-11-01T03:05:12.000Z,"{'times': -0.6978008340903163, 'currency': 'us...",2026-09-09T09:14:20.000Z
99,xdce-crowd-sale,xdc,XDC Network,https://coin-images.coingecko.com/coins/images...,0.028710,572706423,99,1092936463,8.338859e+06,0.029306,...,3.806569e+10,NaN,0.192754,-85.10536,2021-08-20T20:39:48.000Z,0.000395,7.162517e+03,2019-07-21T16:00:00.000Z,"{'times': 0.5202114800549296, 'currency': 'eth...",2026-09-09T09:14:20.000Z

In [3]:
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,79521.000000,1596907659479,1,1596917360999,3.401496e+10,79701.000000,...,2.008179e+07,2.100000e+07,126080.00,-36.92831,2025-10-06T10:57:42.000Z,67.810000,1.171716e+05,2013-07-05T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2511.780000,306518201478,2,306518201478,1.198981e+10,2521.510000,...,1.220326e+08,NaN,4946.05,-49.21649,2025-08-24T11:21:03.000Z,0.432979,5.800154e+05,2015-10-19T16:00:00.000Z,"{'times': 41.23061842109489, 'currency': 'btc'...",2026-09-09T09:14:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999752,183414602480,3,188880189741,5.250357e+10,0.999995,...,1.889271e+11,NaN,1.32,-24.43837,2018-07-23T16:00:00.000Z,0.572521,7.462283e+01,2015-03-01T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,756.770000,100774371434,4,100774365637,9.948938e+08,757.670000,...,1.331614e+08,2.000000e+08,1369.99,-44.76087,2025-10-13T00:41:24.000Z,0.039818,1.900491e+06,2017-10-18T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.430000,89895396694,5,143251551449,2.588803e+09,1.450000,...,9.998563e+10,1.000000e+11,3.65,-60.71386,2025-07-17T19:40:53.000Z,0.002686,5.322878e+04,2014-05-21T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z

In [4]:
df.tail()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
95,official-trump,trump,Official Trump,https://coin-images.coingecko.com/coins/images...,2.260000,617543636,95,2260928999,158756699.0,2.290000,...,1.000000e+09,1.000000e+09,73.430000,-96.92074,2025-01-19T03:50:34.000Z,1.370000,6.501702e+01,2026-08-13T18:40:30.000Z,NaN,2026-09-09T09:14:20.000Z
96,ether-fi,ethfi,Ether.fi,https://coin-images.coingecko.com/coins/images...,0.630890,609010350,96,609010350,72381323.0,0.639674,...,9.653500e+08,1.000000e+09,8.530000,-92.60293,2024-03-27T15:14:46.000Z,0.266530,1.367049e+02,2026-06-05T19:19:15.000Z,NaN,2026-09-09T09:14:20.000Z
97,aerodrome-finance,aero,Aerodrome Finance,https://coin-images.coingecko.com/coins/images...,0.607918,599747778,97,1199852440,70557953.0,0.653594,...,1.973685e+09,NaN,2.320000,-73.76200,2024-12-07T06:00:38.000Z,0.000019,3.266525e+06,2023-10-16T17:23:50.000Z,NaN,2026-09-09T09:14:20.000Z
98,beldex,bdx,Beldex,https://coin-images.coingecko.com/coins/images...,0.075553,594556619,98,750847875,11843723.0,0.077927,...,9.939514e+09,NaN,0.450785,-83.23974,2018-12-16T16:00:00.000Z,0.000275,2.735518e+04,2019-11-01T03:05:12.000Z,"{'times': -0.6978008340903163, 'currency': 'us...",2026-09-09T09:14:20.000Z
99,xdce-crowd-sale,xdc,XDC Network,https://coin-images.coingecko.com/coins/images...,0.028710,572706423,99,1092936463,8338859.0,0.029306,...,3.806569e+10,NaN,0.192754,-85.10536,2021-08-20T20:39:48.000Z,0.000395,7.162517e+03,2019-07-21T16:00:00.000Z,"{'times': 0.5202114800549296, 'currency': 'eth...",2026-09-09T09:14:20.000Z

In [5]:
df.isna().sum()

id                                   0
symbol                               0
name                                 0
image                                0
current_price                        0
market_cap                           0
market_cap_rank                      0
fully_diluted_valuation              0
total_volume                         0
high_24h                             0
low_24h                              0
price_change_24h                     1
price_change_percentage_24h          1
market_cap_change_24h                1
market_cap_change_percentage_24h     1
circulating_supply                   0
total_supply                         0
max_supply                          48
ath                                  0
ath_change_percentage                0
ath_date                             0
atl                                  0
atl_change_percentage                0
atl_date                             0
roi                                 90
last_updated                         0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                100 non-null    object
 1   symbol                            100 non-null    object
 2   name                              100 non-null    object
 3   image                             100 non-null    object
 4   current_price                     100 non-null    float64
 5   market_cap                        100 non-null    int64
 6   market_cap_rank                   100 non-null    int64
 7   fully_diluted_valuation           100 non-null    int64
 8   total_volume                      100 non-null    float64
 9   high_24h                          100 non-null    float64
 10  low_24h                           100 non-null    float64
 11  price_change_24h                  99 non-null     float64
 12  price_change_percentage_24h       99 non-null     float64
 13  market_cap_change_24h             99 non-null     float64
 14  market_cap_change_percentage_24h  99 non-null     float64
 15  circulating_supply                100 non-null    float64
 16  total_supply                      100 non-null    float64
 17  max_supply                        52 non-null     float64
 18  ath                               100 non-null    float64
 19  ath_change_percentage             100 non-null    float64
 20  ath_date                          100 non-null    object
 21  atl                               100 non-null    float64
 22  atl_change_percentage             100 non-null    float64
 23  atl_date                          100 non-null    object
 24  roi                               10 non-null     object
 25  last_updated                      100 non-null    object
dtypes: float64(15), int64(3), object(8)
memory usage: 20.4+ KB

In [7]:
df.shape

(100, 26)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,79521.000000,1596907659479,1,1596917360999,3.401496e+10,79701.000000,...,2.008179e+07,2.100000e+07,126080.000000,-36.92831,2025-10-06T10:57:42.000Z,67.810000,1.171716e+05,2013-07-05T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2511.780000,306518201478,2,306518201478,1.198981e+10,2521.510000,...,1.220326e+08,NaN,4946.050000,-49.21649,2025-08-24T11:21:03.000Z,0.432979,5.800154e+05,2015-10-19T16:00:00.000Z,"{'times': 41.23061842109489, 'currency': 'btc'...",2026-09-09T09:14:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999752,183414602480,3,188880189741,5.250357e+10,0.999995,...,1.889271e+11,NaN,1.320000,-24.43837,2018-07-23T16:00:00.000Z,0.572521,7.462283e+01,2015-03-01T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,756.770000,100774371434,4,100774365637,9.948938e+08,757.670000,...,1.331614e+08,2.000000e+08,1369.990000,-44.76087,2025-10-13T00:41:24.000Z,0.039818,1.900491e+06,2017-10-18T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.430000,89895396694,5,143251551449,2.588803e+09,1.450000,...,9.998563e+10,1.000000e+11,3.650000,-60.71386,2025-07-17T19:40:53.000Z,0.002686,5.322878e+04,2014-05-21T16:00:00.000Z,NaN,2026-09-09T09:14:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,official-trump,trump,Official Trump,https://coin-images.coingecko.com/coins/images...,2.260000,617543636,95,2260928999,1.587567e+08,2.290000,...,1.000000e+09,1.000000e+09,73.430000,-96.92074,2025-01-19T03:50:34.000Z,1.370000,6.501702e+01,2026-08-13T18:40:30.000Z,NaN,2026-09-09T09:14:20.000Z
96,ether-fi,ethfi,Ether.fi,https://coin-images.coingecko.com/coins/images...,0.630890,609010350,96,609010350,7.238132e+07,0.639674,...,9.653500e+08,1.000000e+09,8.530000,-92.60293,2024-03-27T15:14:46.000Z,0.266530,1.367049e+02,2026-06-05T19:19:15.000Z,NaN,2026-09-09T09:14:20.000Z
97,aerodrome-finance,aero,Aerodrome Finance,https://coin-images.coingecko.com/coins/images...,0.607918,599747778,97,1199852440,7.055795e+07,0.653594,...,1.973685e+09,NaN,2.320000,-73.76200,2024-12-07T06:00:38.000Z,0.000019,3.266525e+06,2023-10-16T17:23:50.000Z,NaN,2026-09-09T09:14:20.000Z
98,beldex,bdx,Beldex,https://coin-images.coingecko.com/coins/images...,0.075553,594556619,98,750847875,1.184372e+07,0.077927,...,9.939514e+09,NaN,0.450785,-83.23974,2018-12-16T16:00:00.000Z,0.000275,2.735518e+04,2019-11-01T03:05:12.000Z,"{'times': -0.6978008340903163, 'currency': 'us...",2026-09-09T09:14:20.000Z
99,xdce-crowd-sale,xdc,XDC Network,https://coin-images.coingecko.com/coins/images...,0.028710,572706423,99,1092936463,8.338859e+06,0.029306,...,3.806569e+10,NaN,0.192754,-85.10536,2021-08-20T20:39:48.000Z,0.000395,7.162517e+03,2019-07-21T16:00:00.000Z,"{'times': 0.5202114800549296, 'currency': 'eth...",2026-09-09T09:14:20.000Z

In [10]:
# 1. MISSING VALUES
# Intelligent filling using median

numeric_cols = [
    "current_price",
    "market_cap",
    "fully_diluted_valuation",
    "total_volume",
    "high_24h",
    "low_24h",
    "price_change_24h",
    "price_change_percentage_24h",
    "market_cap_change_24h",
    "circulating_supply",
    "total_supply",
    "max_supply"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill normal numeric missing values with median
for col in df.select_dtypes(include="number").columns:
    df[col] = df[col].fillna(df[col].median())

df[numeric_cols].isna().sum()

current_price                  0
market_cap                     0
fully_diluted_valuation        0
total_volume                   0
high_24h                       0
low_24h                        0
price_change_24h               0
price_change_percentage_24h    0
market_cap_change_24h          0
circulating_supply             0
total_supply                   0
max_supply                     0
dtype: int64

In [11]:
# 2. INCORRECT DATA TYPES
# Convert price, market_cap and volume to float

for col in ["current_price", "market_cap", "total_volume"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce").astype(float)

df.dtypes[["current_price", "market_cap", "total_volume"]]

current_price    float64
market_cap       float64
total_volume     float64
dtype: object

In [12]:
# 3. EXTREME OUTLIERS - IQR

outlier_cols = [
    "current_price",
    "market_cap",
    "total_volume"
]

df["IQR_Outlier"] = False

for col in outlier_cols:
    if col in df.columns:

        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR

        df.loc[
            (df[col] < lower_limit) |
            (df[col] > upper_limit),
            "IQR_Outlier"
        ] = True

df["IQR_Outlier"].value_counts()

IQR_Outlier
False    69
True     31
Name: count, dtype: int64

In [13]:
# 4. EXTREME OUTLIERS - ISOLATION FOREST
features = [
    "current_price",
    "market_cap",
    
    "total_volume"
]

model = IsolationForest(
    contamination=0.05,
    random_state=42
)

df["Isolation_Forest_Outlier"] = (
    model.fit_predict(df[features]) == -1
)
df["Isolation_Forest_Outlier"].value_counts()

Isolation_Forest_Outlier
False    95
True      5
Name: count, dtype: int64

In [14]:
# 5. INCONSISTENT NULLS
# max_supply and total_supply handling

# max_supply can legitimately be unavailable
# so keep missing max_supply as NaN

# total_supply: fill missing values using circulating supply
if "total_supply" in df.columns and "circulating_supply" in df.columns:

    df["total_supply"] = df["total_supply"].fillna(
        df["circulating_supply"]
    )

df[["total_supply", "circulating_supply"]].isna().sum()

total_supply          0
circulating_supply    0
dtype: int64

In [15]:
# 6. DATE FORMAT
# Convert last_updated to datetime


if "last_updated" in df.columns:

    df["last_updated"] = pd.to_datetime(
        df["last_updated"],
        errors="coerce"
    )

df["last_updated"].dtypes

datetime64[ns, UTC]

In [16]:
# 7. DUPLICATE COINS
# Remove duplicates based on ID or symbol


if "id" in df.columns:

    df = df.drop_duplicates(
        subset="id",
        keep="first"
    )

elif "symbol" in df.columns:

    df = df.drop_duplicates(
        subset="symbol",
        keep="first"
    )

df.duplicated().sum()

np.int64(0)

In [17]:
# 8. NEGATIVE OR ZERO PRICES
# Filter invalid records


if "current_price" in df.columns:

    df = df[
        df["current_price"] > 0
    ]

df["current_price"].min()

1.7e-06

In [18]:
# 9. PERCENTAGE COLUMNS
# Handle missing % change values


percentage_cols = [
    col for col in df.columns
    if "percentage" in col.lower()
]

for col in percentage_cols:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

    df[col] = df[col].fillna(0)

df[percentage_cols].isna().sum()

price_change_percentage_24h         0
market_cap_change_percentage_24h    0
ath_change_percentage               0
atl_change_percentage               0
dtype: int64

In [19]:
import numpy as np
# 10. FEATURE ENGINEERING
# Market Cap Category


if "market_cap" in df.columns:

    df["Market_Cap_Category"] = pd.cut(
        df["market_cap"],
        bins=[
            -np.inf,
            100_000_000,
            1_000_000_000,
            10_000_000_000,
            np.inf
        ],
        labels=[
            "Small",
            "Medium",
            "Large",
            "Mega"
        ]
    )

df["Market_Cap_Category"].value_counts()

Market_Cap_Category
Large     61
Medium    26
Mega      13
Small      0
Name: count, dtype: int64

In [20]:
# 11. FEATURE ENGINEERING
# Volatility Score


if "total_volume" in df.columns:

    df["Volatility_Score"] = (
        df["total_volume"] /
        df["total_volume"].median()
    )

df["Volatility_Score"].describe()

count    100.000000
mean      17.353502
std       79.387895
min        0.000000
25%        0.143394
50%        1.000000
75%        3.003474
max      644.864303
Name: Volatility_Score, dtype: float64

In [21]:
# 12. FEATURE ENGINEERING
# Supply Ratio


if (
    "circulating_supply" in df.columns
    and "total_supply" in df.columns
):

    df["Supply_Ratio"] = (
        df["circulating_supply"] /
        df["total_supply"].replace(0, np.nan)
    )

    df["Supply_Ratio"] = df["Supply_Ratio"].clip(
        lower=0,
        upper=1
    )

df["Supply_Ratio"].describe()

count    100.000000
mean       0.827002
std        0.246485
min        0.232853
25%        0.663356
50%        0.999637
75%        1.000000
max        1.000000
Name: Supply_Ratio, dtype: float64

In [22]:

# 13. FINAL CLEANING


df = df.replace(
    [np.inf, -np.inf],
    np.nan
)

In [23]:
# 14. DISPLAY RESULTS


print("Dataset Shape:")
print(df.shape)
print()
print("\nMissing Values:")
print(df.isnull().sum())
print()
print("\nData Types:")
print(df.dtypes)
print()
print("\nFirst 5 Rows:")
print(df.head())

Dataset Shape:
(100, 31)


Missing Values:
id                                   0
symbol                               0
name                                 0
image                                0
current_price                        0
market_cap                           0
market_cap_rank                      0
fully_diluted_valuation              0
total_volume                         0
high_24h                             0
low_24h                              0
price_change_24h                     0
price_change_percentage_24h          0
market_cap_change_24h                0
market_cap_change_percentage_24h     0
circulating_supply                   0
total_supply                         0
max_supply                           0
ath                                  0
ath_change_percentage                0
ath_date                             0
atl                                  0
atl_change_percentage                0
atl_date                             0
roi                                 90
last_updated                         0
IQR_Outlier                          0
Isolation_Forest_Outlier             0
Market_Cap_Category                  0
Volatility_Score                     0
Supply_Ratio                         0
dtype: int64


Data Types:
id                                               object
symbol                                           object
name                                             object
image                                            object
current_price                                   float64
market_cap                                      float64
market_cap_rank                                   int64
fully_diluted_valuation                           int64
total_volume                                    float64
high_24h                                        float64
low_24h                                         float64
price_change_24h                                float64
price_change_percentage_24h                     float64
market_cap_change_24h                           float64
market_cap_change_percentage_24h                float64
circulating_supply                              float64
total_supply                                    float64
max_supply                                      float64
ath                                             float64
ath_change_percentage                           float64
ath_date                                         object
atl                                             float64
atl_change_percentage                           float64
atl_date                                         object
roi                                              object
last_updated                        datetime64[ns, UTC]
IQR_Outlier                                        bool
Isolation_Forest_Outlier                           bool
Market_Cap_Category                            category
Volatility_Score                                float64
Supply_Ratio                                    float64
dtype: object


First 5 Rows:
            id symbol      name  \
0      bitcoin    btc   Bitcoin
1     ethereum    eth  Ethereum
2       tether   usdt    Tether
3  binancecoin    bnb       BNB
4       ripple    xrp       XRP

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   79521.000000
1  https://coin-images.coingecko.com/coins/images...    2511.780000
2  https://coin-images.coingecko.com/coins/images...       0.999752
3  https://coin-images.coingecko.com/coins/images...     756.770000
4  https://coin-images.coingecko.com/coins/images...       1.430000

     market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1.596908e+12                1            1596917360999  3.401496e+10
1  3.065182e+11                2             306518201478  1.198981e+10
2  1.834146e+11                3             188880189741  5.250357e+10
3  1.007744e+11                4             100774365637  9.948938e+08
4  8.989540e+10                5             143251551449  2.588803e+09

       high_24h  ...        atl  atl_change_percentage  \
0  79701.000000  ...  67.810000           1.171716e+05
1   2521.510000  ...   0.432979           5.800154e+05
2      0.999995  ...   0.572521           7.462283e+01
3    757.670000  ...   0.039818           1.900491e+06
4      1.450000  ...   0.002686           5.322878e+04

                   atl_date  \
0  2013-07-05T16:00:00.000Z
1  2015-10-19T16:00:00.000Z
2  2015-03-01T16:00:00.000Z
3  2017-10-18T16:00:00.000Z
4  2014-05-21T16:00:00.000Z

                                                 roi  \
0                                                NaN
1  {'times': 41.23061842109489, 'currency': 'btc'...
2                                                NaN
3                                                NaN
4                                                NaN

               last_updated  IQR_Outlier  Isolation_Forest_Outlier  \
0 2026-09-09 09:14:20+00:00         True                      True
1 2026-09-09 09:14:20+00:00         True                      True
2 2026-09-09 09:14:20+00:00         True                      True
3 2026-09-09 09:14:20+00:00         True                      True
4 2026-09-09 09:14:20+00:00         True                     False

   Market_Cap_Category  Volatility_Score  Supply_Ratio
0                 Mega        417.781799      0.999994
1                 Mega        147.262341      1.000000
2                 Mega        644.864303      0.971063
3                 Mega         12.219579      1.000000
4                 Mega         31.796446      0.627535

[5 rows x 31 columns]

In [24]:

# 15. SAVE CLEANED DATA


df.to_csv(
    "crypto_data_cleaned.csv",
    index=False
)

print("\nCleaned dataset saved successfully!")

Cleaned dataset saved successfully!