In [29]:
import pandas as pd
import numpy as np

In [30]:
df=pd.read_csv(r"C:\All project\Advanced Multi-Source Data Pipeline\books_data.csv")
df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [31]:
# converting invalid type to float
# Price format > Remove £ symbol and convert to float
print(df.shape)
print(df.dtypes)

(20, 4)
Title           object
Price           object
Rating          object
Availability    object
dtype: object

In [32]:
df["Price"] = df["Price"].str.replace('Â£', '')# Remove £ and commas, then convert to float
df["Price"] = pd.to_numeric(df["Price"], errors='coerce')  # Convert to numeric, setting errors to NaN
df["Price"].dtypes

dtype('float64')

In [33]:
df["Price"].unique()

array([51.77, 53.74, 50.1 , 47.82, 54.23, 22.65, 33.34, 17.93, 22.6 ,
       52.15, 13.99, 20.66, 17.46, 52.29, 35.02, 57.25, 23.88, 37.59,
       51.33, 45.17])

In [34]:
# Rating text Convert "One", "Two"... → numerical (1–5)
df["Rating"] = df["Rating"].replace({
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
})
df["Rating"].head(5)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_10904\3491820223.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Rating"] = df["Rating"].replace({

0    3
1    1
2    1
3    4
4    5
Name: Rating, dtype: int64

In [35]:
# Availability text  - Extract number of books in stock

df["Stock"] = df["Availability"].str.extract(r"(\d+)").astype(float)

df["Stock"] = df["Availability"].replace({
    "In stock": 1,
    "Out of stock": 0
})
print(df["Stock"])

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: Stock, dtype: int64

C:\Users\lenovo\AppData\Local\Temp\ipykernel_10904\1316811430.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Stock"] = df["Availability"].replace({

In [36]:
df["Stock"].dtypes

dtype('int64')

In [37]:
# Extra spaces / special chars : Clean title and text columns
df["Title"] = df["Title"].str.strip().str.replace(r'[^\w\s]', '', regex=True)  # Remove special characters
print(df["Title"])

0                                  A Light in the Attic
1                                    Tipping the Velvet
2                                            Soumission
3                                         Sharp Objects
4                  Sapiens A Brief History of Humankind
5                                       The Requiem Red
6     The Dirty Little Secrets of Getting Your Dream...
7     The Coming Woman A Novel Based on the Life of ...
8     The Boys in the Boat Nine Americans and Their ...
9                                       The Black Maria
10           Starving Hearts Triangular Trade Trilogy 1
11                                 Shakespeares Sonnets
12                                          Set Me Free
13    Scott Pilgrims Precious Little Life Scott Pilg...
14                            Rip it Up and Start Again
15    Our Band Could Be Your Life Scenes from the Am...
16                                                 Olio
17    Mesaerion The Best Science Fiction Stories 180...
18                         Libertarianism for Beginners
19                               Its Only the Himalayas
Name: Title, dtype: object

In [40]:
df["Rating"].unique

<bound method Series.unique of 0     3
1     1
2     1
3     4
4     5
5     1
6     4
7     3
8     4
9     1
10    2
11    4
12    5
13    5
14    5
15    3
16    1
17    1
18    2
19    2
Name: Rating, dtype: int64>

In [ ]:
# Duplicates : Removing duplicate book titles
# Check duplicate rows
print(df.duplicated().sum())
# Remove duplicate rows
df = df.drop_duplicates()

In [39]:
# Data type conversion: Ensures correct numerical types
print(df.dtypes)

Title            object
Price           float64
Rating            int64
Availability     object
Stock             int64
dtype: object

In [45]:
# Feature Engineering : Price range categories, Rating groups, Stock status

# price range categories
df["Price_Range"] = pd.cut(
    df["Price"],
    bins=[0, 20, 40, 60, float("inf")],
    labels=["Low", "Medium", "High", "Very High"]
)

# rating groups
df["Rating_Group"] = pd.cut(
    df["Rating"],
    bins=[0, 2, 3, 4, 5],
    labels=["Poor", "Average", "Good", "Excellent"]
)

# Stock status
df["Stock_Status"] = df["Availability"].replace({
    "In stock": "Available",
    "Out of stock": "Not Available"
})

In [46]:
df.head()

,Title,Price,Rating,Availability,Stock,Price_Range,Rating_Group,Stock_Status
0,A Light in the Attic,51.77,3,In stock,1,High,Average,Available
1,Tipping the Velvet,53.74,1,In stock,1,High,Poor,Available
2,Soumission,50.10,1,In stock,1,High,Poor,Available
3,Sharp Objects,47.82,4,In stock,1,High,Good,Available
4,Sapiens A Brief History of Humankind,54.23,5,In stock,1,High,Excellent,Available

In [49]:
print(df.to_csv("books_cleaned.csv", index = False))
print("Succesfully Done")

None
Succesfully Done